# Generated by Django 3.2.18 on 2023-04-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
    ]
