# Generated by Django 3.2.18 on 2023-04-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0003_attraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='id',
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
