# Generated by Django 3.2.18 on 2023-04-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0007_cuisine_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attractions', models.ManyToManyField(to='wnader.Attraction')),
                ('cuisines', models.ManyToManyField(to='wnader.Cuisine')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wnader.destination')),
            ],
            options={
                'verbose_name': 'CustomerPlan',
                'verbose_name_plural': 'CustomerPlans',
            },
        ),
    ]
