# Generated by Django 3.2.18 on 2023-04-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0008_customerplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnader.destination'),
        ),
    ]
