# Generated by Django 3.2.18 on 2023-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0009_alter_customerplan_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPlan',
        ),
    ]
