# Generated by Django 3.2.18 on 2023-04-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0011_customerplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplan',
            name='people',
            field=models.IntegerField(default=1),
        ),
    ]
