# Generated by Django 3.2.18 on 2023-04-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0012_customerplan_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'AttractionCategory',
                'verbose_name_plural': 'AttractionCategories',
            },
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.AlterField(
            model_name='customerplan',
            name='attractions',
            field=models.ManyToManyField(to='wnader.AttractionCategory'),
        ),
    ]
