# Generated by Django 3.2.18 on 2023-05-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0015_amanates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('location', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'PlanAttraction',
                'verbose_name_plural': 'PlanAttractions',
            },
        ),
        migrations.CreateModel(
            name='PlanRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=255)),
                ('review_star', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('stars', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PlanRestaurant',
                'verbose_name_plural': 'PlanRestaurants',
            },
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.AlterModelOptions(
            name='amanates',
            options={'verbose_name': 'Amanate', 'verbose_name_plural': 'Amanates'},
        ),
        migrations.RemoveField(
            model_name='customerplan',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='customerplan',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='planrestaurant',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnader.customerplan'),
        ),
        migrations.AddField(
            model_name='planattraction',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnader.customerplan'),
        ),
    ]
