# Generated by Django 3.2.18 on 2023-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0016_auto_20230510_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerplan',
            name='budget',
        ),
        migrations.AddField(
            model_name='customerplan',
            name='max_budget',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='min_budget',
            field=models.IntegerField(default=25),
        ),
    ]
