# Generated by Django 3.2.18 on 2023-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0017_auto_20230510_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='max_budget',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='customerplan',
            name='min_budget',
            field=models.FloatField(default=25),
        ),
    ]
