# Generated by Django 3.2.18 on 2023-05-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0018_auto_20230510_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planattraction',
            options={'verbose_name': 'PlanRestaurant', 'verbose_name_plural': 'PlanRestaurants'},
        ),
        migrations.DeleteModel(
            name='PlanRestaurant',
        ),
    ]
