# Generated by Django 3.2.18 on 2023-05-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0019_auto_20230512_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planattraction',
            options={'verbose_name': 'PlanAttraction', 'verbose_name_plural': 'PlanAttractions'},
        ),
        migrations.CreateModel(
            name='PlanRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_detail', models.JSONField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnader.customerplan')),
            ],
            options={
                'verbose_name': 'PlanRestaurant',
                'verbose_name_plural': 'PlanRestaurants',
            },
        ),
    ]
