# Generated by Django 3.2.18 on 2023-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0021_auto_20230512_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrestaurant',
            name='plan',
        ),
        migrations.AddField(
            model_name='customerplan',
            name='attraction_detail',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='attractions',
            field=models.ManyToManyField(to='wnader.AttractionCategory'),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='cuisines',
            field=models.ManyToManyField(to='wnader.Cuisine'),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='hotel_detail',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customerplan',
            name='restaurant_detail',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='PlanAttraction',
        ),
        migrations.DeleteModel(
            name='PlanRestaurant',
        ),
    ]
