# Generated by Django 3.2.18 on 2023-05-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0022_auto_20230512_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPlan',
        ),
    ]
