# Generated by Django 3.2.18 on 2023-05-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0023_delete_customerplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('attractions', models.TextField()),
                ('cuisines', models.TextField()),
                ('attraction_detail', models.JSONField(null=True)),
                ('restaurant_detail', models.JSONField(null=True)),
                ('hotel_detail', models.JSONField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('people', models.IntegerField(default=1)),
                ('min_budget', models.FloatField(default=25)),
                ('max_budget', models.FloatField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnader.customer')),
            ],
            options={
                'verbose_name': 'CustomerPlan',
                'verbose_name_plural': 'CustomerPlans',
            },
        ),
    ]
