# Generated by Django 3.2.18 on 2023-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0024_customerplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='attractions',
            field=models.JSONField(),
        ),
    ]
