# Generated by Django 3.2.18 on 2023-05-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0025_alter_customerplan_attractions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amanates',
            new_name='Amenities',
        ),
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
    ]
