# Generated by Django 3.2.18 on 2023-05-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0027_remove_amenities_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
