# Generated by Django 3.2.18 on 2023-05-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0028_delete_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('amenities', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('review_star', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('categories', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnader.attractioncategory')),
            ],
            options={
                'verbose_name': 'Attraction',
                'verbose_name_plural': 'Attractions',
            },
        ),
    ]
