# Generated by Django 3.2.18 on 2023-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0029_attraction_hotel_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='Category',
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
