# Generated by Django 3.2.18 on 2023-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnader', '0030_auto_20230515_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerplan',
            name='amenities',
            field=models.TextField(null=True),
        ),
    ]
